const stats = [
  {
    title: "Active Employees",
    value: "16,689",
    iconBg: "#635BFF",
    icon: "fa-light fa-address-card text-xl!",
    bg: "linear-gradient(180deg, rgba(99, 91, 255, 0.12) 0%, rgba(99, 91, 255, 0.03) 100%)",
    link: "/employees",
  },
  {
    title: "Active Projects",
    value: "42",
    iconBg: "#36C76C",
    icon: "fa-light fa-building text-xl!",
    bg: "linear-gradient(180deg, rgba(54, 199, 108, 0.13) 0%, rgba(54, 199, 108, 0.03) 100%)",
    link: "/projects",
  },
  {
    title: "Active Users",
    value: "20",
    icon: "pi pi-users text-2xl!",
    iconBg: "#16CDC7",
    bg: "linear-gradient(180deg, rgba(22, 205, 199, 0.13) 0%, rgba(22, 205, 199, 0.03) 100%)",
    link: "/users",
  },
  {
    title: "Active Loans",
    value: "160",
    icon: "fa-light fa-newspaper text-xl!",
    iconBg: "#F89F7F",
    bg: "linear-gradient(180deg, #FFC6B1 0%, rgba(255, 198, 177, 0.1) 100%)",
    link: "/loans",
  },
];

const projects = [
  {
    label: "All Projects",
    value: "0",
  },
  {
    label: "ABC Company ABC Company ABC Company ABC Company",
    value: "100",
  },
  {
    label: "XYZ Company",
    value: "200",
  },
  {
    label: "LMN Company",
    value: "300",
  },
  {
    label: "PQR Company",
    value: "400",
  },
  {
    label: "RST Company",
    value: "500",
  },
];

interface ProjectExpense {
  id: number;
  name: string;
  image: string;
  status: "active" | "inactive";
  expenses: number;
}

const expensesByProject: ProjectExpense[] = [
  {
    id: 1,
    name: "Jeddah Cash Salaries",
    image:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&h=100&fit=crop",
    status: "active",
    expenses: 3500,
  },
  {
    id: 2,
    name: "Riyadh Cash Salaries",
    image:
      "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=100&h=100&fit=crop",
    status: "active",
    expenses: 3500,
  },
  {
    id: 3,
    name: "Admin & Com. Center",
    image:
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=100&h=100&fit=crop",
    status: "inactive",
    expenses: 3500,
  },
  {
    id: 4,
    name: "Al-Omran Residence",
    image:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=100&h=100&fit=crop",
    status: "inactive",
    expenses: 3500,
  },
  {
    id: 5,
    name: "Dammam Office Complex",
    image:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=100&h=100&fit=crop",
    status: "active",
    expenses: 4200,
  },
  {
    id: 6,
    name: "Khobar Warehouse",
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=100&h=100&fit=crop",
    status: "inactive",
    expenses: 2800,
  },
];

const branches = [
  { label: "All Branches", value: "all" },
  { label: "Jeddah Branch", value: "jeddah" },
  { label: "Riyadh Branch", value: "riyadh" },
  { label: "Dammam Branch", value: "dammam" },
];

const months = [
  { label: "Jan 2025", value: "2025-01" },
  { label: "Feb 2025", value: "2025-02" },
  { label: "Mar 2025", value: "2025-03" },
  { label: "Apr 2025", value: "2025-04" },
  { label: "May 2025", value: "2025-05" },
  { label: "Jun 2025", value: "2025-06" },
  { label: "Jul 2025", value: "2025-07" },
  { label: "Aug 2025", value: "2025-08" },
  { label: "Sep 2025", value: "2025-09" },
  { label: "Oct 2025", value: "2025-10" },
  { label: "Nov 2025", value: "2025-11" },
  { label: "Dec 2025", value: "2025-12" },
];

interface Employee {
  id: number;
  empCode: string;
  empPicture: string;
  empNameEn: string;
  empNameAr: string;
  empGender: string;
  empIdNo: string;
  empDesignation: string;
  empPayrollSection: string;
  empProfession: string;
  empHourlyRate: string;
  empOpeningBalance: string;
  empNationality: string;
  empContactNo: string;
  empIsFixed: boolean;
  empIsCardDelivered: boolean;
  empCardDocLink: string;
}

const employees: Employee[] = [
  {
    id: 1,
    empCode: "EMP001",
    empPicture:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    empNameEn: "Ahmed Al-Mansouri",
    empNameAr: "أحمد المنصوري",
    empGender: "Male",
    empIdNo: "1234567890",
    empDesignation: "Senior Engineer",
    empPayrollSection: "Engineering",
    empProfession: "Civil Engineer",
    empHourlyRate: "150.00",
    empOpeningBalance: "5,000.00",
    empNationality: "Saudi",
    empContactNo: "+966501234567",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 2,
    empCode: "EMP002",
    empPicture:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    empNameEn: "Fatima Al-Zahra",
    empNameAr: "فاطمة الزهراء",
    empGender: "Female",
    empIdNo: "2345678901",
    empDesignation: "HR Manager",
    empPayrollSection: "Administration",
    empProfession: "Human Resources",
    empHourlyRate: "120.00",
    empOpeningBalance: "3,500.00",
    empNationality: "Saudi",
    empContactNo: "+966502345678",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 3,
    empCode: "EMP003",
    empPicture:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    empNameEn: "Mohammed Al-Rashid",
    empNameAr: "محمد الراشد",
    empGender: "Male",
    empIdNo: "3456789012",
    empDesignation: "Project Manager",
    empPayrollSection: "Management",
    empProfession: "Project Management",
    empHourlyRate: "180.00",
    empOpeningBalance: "7,500.00",
    empNationality: "Saudi",
    empContactNo: "+966503456789",
    empIsFixed: true,
    empIsCardDelivered: false,
    empCardDocLink: "#",
  },
  {
    id: 4,
    empCode: "EMP004",
    empPicture:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    empNameEn: "Sara Al-Mutairi",
    empNameAr: "سارة المطيري",
    empGender: "Female",
    empIdNo: "4567890123",
    empDesignation: "Accountant",
    empPayrollSection: "Finance",
    empProfession: "Accounting",
    empHourlyRate: "100.00",
    empOpeningBalance: "2,000.00",
    empNationality: "Saudi",
    empContactNo: "+966504567890",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 5,
    empCode: "EMP005",
    empPicture:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    empNameEn: "Khalid Al-Otaibi",
    empNameAr: "خالد العتيبي",
    empGender: "Male",
    empIdNo: "5678901234",
    empDesignation: "Site Supervisor",
    empPayrollSection: "Operations",
    empProfession: "Construction",
    empHourlyRate: "90.00",
    empOpeningBalance: "1,500.00",
    empNationality: "Saudi",
    empContactNo: "+966505678901",
    empIsFixed: false,
    empIsCardDelivered: false,
    empCardDocLink: "#",
  },
  {
    id: 6,
    empCode: "EMP006",
    empPicture:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
    empNameEn: "Noura Al-Dosari",
    empNameAr: "نورة الدوسري",
    empGender: "Female",
    empIdNo: "6789012345",
    empDesignation: "IT Specialist",
    empPayrollSection: "IT",
    empProfession: "Information Technology",
    empHourlyRate: "130.00",
    empOpeningBalance: "4,000.00",
    empNationality: "Saudi",
    empContactNo: "+966506789012",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 7,
    empCode: "EMP007",
    empPicture:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop",
    empNameEn: "Omar Al-Harbi",
    empNameAr: "عمر الحربي",
    empGender: "Male",
    empIdNo: "7890123456",
    empDesignation: "Mechanical Engineer",
    empPayrollSection: "Engineering",
    empProfession: "Mechanical Engineering",
    empHourlyRate: "140.00",
    empOpeningBalance: "3,200.00",
    empNationality: "Saudi",
    empContactNo: "+966507890123",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 8,
    empCode: "EMP008",
    empPicture:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
    empNameEn: "Layla Al-Shammari",
    empNameAr: "ليلى الشمري",
    empGender: "Female",
    empIdNo: "8901234567",
    empDesignation: "Administrative Assistant",
    empPayrollSection: "Administration",
    empProfession: "Administration",
    empHourlyRate: "75.00",
    empOpeningBalance: "1,200.00",
    empNationality: "Saudi",
    empContactNo: "+966508901234",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 9,
    empCode: "EMP009",
    empPicture:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop",
    empNameEn: "Yousef Al-Ghamdi",
    empNameAr: "يوسف الغامدي",
    empGender: "Male",
    empIdNo: "9012345678",
    empDesignation: "Electrician",
    empPayrollSection: "Operations",
    empProfession: "Electrical",
    empHourlyRate: "85.00",
    empOpeningBalance: "1,800.00",
    empNationality: "Saudi",
    empContactNo: "+966509012345",
    empIsFixed: false,
    empIsCardDelivered: false,
    empCardDocLink: "#",
  },
  {
    id: 10,
    empCode: "EMP010",
    empPicture: "",
    empNameEn: "Mariam Al-Qahtani",
    empNameAr: "مريم القحطاني",
    empGender: "Female",
    empIdNo: "0123456789",
    empDesignation: "Quality Control",
    empPayrollSection: "Quality",
    empProfession: "Quality Assurance",
    empHourlyRate: "110.00",
    empOpeningBalance: "2,500.00",
    empNationality: "Saudi",
    empContactNo: "+966500123456",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 11,
    empCode: "EMP011",
    empPicture:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    empNameEn: "Faisal Al-Shehri",
    empNameAr: "فيصل الشهري",
    empGender: "Male",
    empIdNo: "1234509876",
    empDesignation: "Architect",
    empPayrollSection: "Engineering",
    empProfession: "Architecture",
    empHourlyRate: "160.00",
    empOpeningBalance: "6,000.00",
    empNationality: "Saudi",
    empContactNo: "+966501234567",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 12,
    empCode: "EMP012",
    empPicture:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    empNameEn: "Hanan Al-Mutlaq",
    empNameAr: "حنان المطلق",
    empGender: "Female",
    empIdNo: "2345610987",
    empDesignation: "Procurement Officer",
    empPayrollSection: "Procurement",
    empProfession: "Procurement",
    empHourlyRate: "95.00",
    empOpeningBalance: "2,200.00",
    empNationality: "Saudi",
    empContactNo: "+966502345678",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 13,
    empCode: "EMP013",
    empPicture:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    empNameEn: "Saud Al-Balawi",
    empNameAr: "سعود البلوي",
    empGender: "Male",
    empIdNo: "3456721098",
    empDesignation: "Safety Officer",
    empPayrollSection: "Safety",
    empProfession: "Safety Management",
    empHourlyRate: "105.00",
    empOpeningBalance: "2,800.00",
    empNationality: "Saudi",
    empContactNo: "+966503456789",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 14,
    empCode: "EMP014",
    empPicture:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
    empNameEn: "Reem Al-Fahad",
    empNameAr: "ريم الفهد",
    empGender: "Female",
    empIdNo: "4567832109",
    empDesignation: "Marketing Specialist",
    empPayrollSection: "Marketing",
    empProfession: "Marketing",
    empHourlyRate: "115.00",
    empOpeningBalance: "3,000.00",
    empNationality: "Saudi",
    empContactNo: "+966504567890",
    empIsFixed: true,
    empIsCardDelivered: false,
    empCardDocLink: "#",
  },
  {
    id: 15,
    empCode: "EMP015",
    empPicture:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    empNameEn: "Nasser Al-Mazrouei",
    empNameAr: "ناصر المزروعي",
    empGender: "Male",
    empIdNo: "5678943210",
    empDesignation: "Warehouse Manager",
    empPayrollSection: "Logistics",
    empProfession: "Warehouse Management",
    empHourlyRate: "125.00",
    empOpeningBalance: "4,500.00",
    empNationality: "Saudi",
    empContactNo: "+966505678901",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 16,
    empCode: "EMP016",
    empPicture:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    empNameEn: "Amal Al-Harbi",
    empNameAr: "أمل الحربي",
    empGender: "Female",
    empIdNo: "6789054321",
    empDesignation: "Legal Advisor",
    empPayrollSection: "Legal",
    empProfession: "Law",
    empHourlyRate: "170.00",
    empOpeningBalance: "8,000.00",
    empNationality: "Saudi",
    empContactNo: "+966506789012",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 17,
    empCode: "EMP017",
    empPicture:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    empNameEn: "Majed Al-Sulami",
    empNameAr: "ماجد السلمي",
    empGender: "Male",
    empIdNo: "7890165432",
    empDesignation: "Plumber",
    empPayrollSection: "Maintenance",
    empProfession: "Plumbing",
    empHourlyRate: "80.00",
    empOpeningBalance: "1,300.00",
    empNationality: "Saudi",
    empContactNo: "+966507890123",
    empIsFixed: false,
    empIsCardDelivered: false,
    empCardDocLink: "#",
  },
  {
    id: 18,
    empCode: "EMP018",
    empPicture:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    empNameEn: "Hala Al-Rashid",
    empNameAr: "هالة الراشد",
    empGender: "Female",
    empIdNo: "8901276543",
    empDesignation: "Receptionist",
    empPayrollSection: "Administration",
    empProfession: "Reception",
    empHourlyRate: "70.00",
    empOpeningBalance: "1,000.00",
    empNationality: "Saudi",
    empContactNo: "+966508901234",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 19,
    empCode: "EMP019",
    empPicture:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    empNameEn: "Turki Al-Anzi",
    empNameAr: "تركي العنزي",
    empGender: "Male",
    empIdNo: "9012387654",
    empDesignation: "Driver",
    empPayrollSection: "Transportation",
    empProfession: "Driving",
    empHourlyRate: "65.00",
    empOpeningBalance: "800.00",
    empNationality: "Saudi",
    empContactNo: "+966509012345",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 20,
    empCode: "EMP020",
    empPicture:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
    empNameEn: "Rana Al-Mutairi",
    empNameAr: "رنا المطيري",
    empGender: "Female",
    empIdNo: "0123498765",
    empDesignation: "Data Entry Clerk",
    empPayrollSection: "Administration",
    empProfession: "Data Entry",
    empHourlyRate: "60.00",
    empOpeningBalance: "900.00",
    empNationality: "Saudi",
    empContactNo: "+966500123456",
    empIsFixed: false,
    empIsCardDelivered: false,
    empCardDocLink: "#",
  },
  {
    id: 21,
    empCode: "EMP021",
    empPicture:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    empNameEn: "Bandar Al-Otaibi",
    empNameAr: "بندر العتيبي",
    empGender: "Male",
    empIdNo: "1234501234",
    empDesignation: "Surveyor",
    empPayrollSection: "Engineering",
    empProfession: "Surveying",
    empHourlyRate: "135.00",
    empOpeningBalance: "3,600.00",
    empNationality: "Saudi",
    empContactNo: "+966501234567",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 22,
    empCode: "EMP022",
    empPicture:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    empNameEn: "Nada Al-Dosari",
    empNameAr: "ندى الدوسري",
    empGender: "Female",
    empIdNo: "2345612345",
    empDesignation: "Nurse",
    empPayrollSection: "Medical",
    empProfession: "Nursing",
    empHourlyRate: "145.00",
    empOpeningBalance: "4,200.00",
    empNationality: "Saudi",
    empContactNo: "+966502345678",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 23,
    empCode: "EMP023",
    empPicture:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop",
    empNameEn: "Hamad Al-Harbi",
    empNameAr: "حمد الحربي",
    empGender: "Male",
    empIdNo: "3456723456",
    empDesignation: "Carpenter",
    empPayrollSection: "Operations",
    empProfession: "Carpentry",
    empHourlyRate: "88.00",
    empOpeningBalance: "1,600.00",
    empNationality: "Saudi",
    empContactNo: "+966503456789",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 24,
    empCode: "EMP024",
    empPicture:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
    empNameEn: "Lina Al-Shammari",
    empNameAr: "لينا الشمري",
    empGender: "Female",
    empIdNo: "4567834567",
    empDesignation: "Secretary",
    empPayrollSection: "Administration",
    empProfession: "Secretarial",
    empHourlyRate: "72.00",
    empOpeningBalance: "1,100.00",
    empNationality: "Saudi",
    empContactNo: "+966504567890",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 25,
    empCode: "EMP025",
    empPicture:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    empNameEn: "Zaid Al-Ghamdi",
    empNameAr: "زيد الغامدي",
    empGender: "Male",
    empIdNo: "5678945678",
    empDesignation: "Security Guard",
    empPayrollSection: "Security",
    empProfession: "Security",
    empHourlyRate: "55.00",
    empOpeningBalance: "700.00",
    empNationality: "Saudi",
    empContactNo: "+966505678901",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 26,
    empCode: "EMP026",
    empPicture: "",
    empNameEn: "Maha Al-Qahtani",
    empNameAr: "مها القحطاني",
    empGender: "Female",
    empIdNo: "6789056789",
    empDesignation: "Graphic Designer",
    empPayrollSection: "Design",
    empProfession: "Graphic Design",
    empHourlyRate: "125.00",
    empOpeningBalance: "3,400.00",
    empNationality: "Saudi",
    empContactNo: "+966506789012",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 27,
    empCode: "EMP027",
    empPicture:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    empNameEn: "Waleed Al-Shehri",
    empNameAr: "وليد الشهري",
    empGender: "Male",
    empIdNo: "7890167890",
    empDesignation: "Welder",
    empPayrollSection: "Operations",
    empProfession: "Welding",
    empHourlyRate: "92.00",
    empOpeningBalance: "1,700.00",
    empNationality: "Saudi",
    empContactNo: "+966507890123",
    empIsFixed: false,
    empIsCardDelivered: false,
    empCardDocLink: "#",
  },
  {
    id: 28,
    empCode: "EMP028",
    empPicture:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
    empNameEn: "Dina Al-Mutlaq",
    empNameAr: "دينا المطلق",
    empGender: "Female",
    empIdNo: "8901278901",
    empDesignation: "Translator",
    empPayrollSection: "Administration",
    empProfession: "Translation",
    empHourlyRate: "108.00",
    empOpeningBalance: "2,600.00",
    empNationality: "Saudi",
    empContactNo: "+966508901234",
    empIsFixed: true,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 29,
    empCode: "EMP029",
    empPicture:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    empNameEn: "Raed Al-Balawi",
    empNameAr: "رائد البلوي",
    empGender: "Male",
    empIdNo: "9012389012",
    empDesignation: "Heavy Equipment Operator",
    empPayrollSection: "Operations",
    empProfession: "Heavy Equipment",
    empHourlyRate: "98.00",
    empOpeningBalance: "2,100.00",
    empNationality: "Saudi",
    empContactNo: "+966509012345",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
  {
    id: 30,
    empCode: "EMP030",
    empPicture:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    empNameEn: "Yasmin Al-Fahad",
    empNameAr: "ياسمين الفهد",
    empGender: "Female",
    empIdNo: "0123490123",
    empDesignation: "Customer Service",
    empPayrollSection: "Customer Service",
    empProfession: "Customer Relations",
    empHourlyRate: "82.00",
    empOpeningBalance: "1,400.00",
    empNationality: "Saudi",
    empContactNo: "+966500123456",
    empIsFixed: false,
    empIsCardDelivered: true,
    empCardDocLink: "#",
  },
];

const designationOptions = [
  { label: "All Designations", value: "0" },
  { label: "Engineer", value: "1" },
  { label: "Manager", value: "2" },
  { label: "Assistant", value: "3" },
  { label: "Other", value: "4" },
];

interface TimesheetEntry {
  id: number;
  rowNumber: number;
  code: string;
  employeeName: string;
  designation: string;
  hasFlag: boolean;
  isLocked: boolean;
  project1: string | null;
  project1Hours: number;
  project1OT: number;
  project2: string | null;
  project2Hours: number;
  project2OT: number;
  totalHours: number;
  remarks: string;
  allowBreakProject1?: boolean;
  allowBreakProject1Value?: boolean;
  allowBreakProject2?: boolean;
  allowBreakProject2Value?: boolean;
}

// Sample data matching the image description
const initialTimesheetData: TimesheetEntry[] = [
  {
    id: 1,
    rowNumber: 1,
    code: "10000",
    employeeName: "REJA, HALIL/HALIL, SALUM SALUM SALUM SALUM",
    designation: "Driver",
    hasFlag: false,
    isLocked: false,
    project1: null,
    project1Hours: 0,
    project1OT: 0,
    project2: null,
    project2Hours: 0,
    project2OT: 0,
    totalHours: 0,
    remarks: "",
    allowBreakProject1: false,
    allowBreakProject1Value: false,
    allowBreakProject2: false,
    allowBreakProject2Value: false,
  },
  {
    id: 2,
    rowNumber: 2,
    code: "20000",
    employeeName: "EMPLOYEE NAME 2",
    designation: "Designation",
    hasFlag: false,
    isLocked: false,
    project1: null,
    project1Hours: 0,
    project1OT: 0,
    project2: null,
    project2Hours: 0,
    project2OT: 0,
    totalHours: 0,
    remarks: "",
    allowBreakProject1: true,
    allowBreakProject1Value: false,
    allowBreakProject2: true,
    allowBreakProject2Value: false,
  },
  {
    id: 3,
    rowNumber: 3,
    code: "30001",
    employeeName: "HUSSEIN ALI SHILAH ISSA",
    designation: "Truck Driver (Low Loader)",
    hasFlag: true,
    isLocked: false,
    project1: null,
    project1Hours: 0,
    project1OT: 0,
    project2: null,
    project2Hours: 0,
    project2OT: 0,
    totalHours: 0,
    remarks: "",
    allowBreakProject1: false,
    allowBreakProject1Value: false,
    allowBreakProject2: false,
    allowBreakProject2Value: false,
  },
  {
    id: 4,
    rowNumber: 4,
    code: "30002",
    employeeName: "IBRAHIM ALI SHILAH ISSA",
    designation: "Foreman Engineer",
    hasFlag: false,
    isLocked: false,
    project1: null,
    project1Hours: 0,
    project1OT: 0,
    project2: null,
    project2Hours: 0,
    project2OT: 0,
    totalHours: 0,
    remarks: "",
    allowBreakProject1: true,
    allowBreakProject1Value: false,
    allowBreakProject2: true,
    allowBreakProject2Value: false,
  },
  {
    id: 5,
    rowNumber: 5,
    code: "30003",
    employeeName: "EMPLOYEE NAME 5",
    designation: "Electrician",
    hasFlag: false,
    isLocked: false,
    project1: null,
    project1Hours: 0,
    project1OT: 0,
    project2: null,
    project2Hours: 0,
    project2OT: 0,
    totalHours: 0,
    remarks: "",
    allowBreakProject1: true,
    allowBreakProject1Value: false,
    allowBreakProject2: true,
    allowBreakProject2Value: false,
  },
  {
    id: 6,
    rowNumber: 6,
    code: "30004",
    employeeName: "ABDI FARAX ABDI SALAH (GEN)",
    designation: "Watchman",
    hasFlag: false,
    isLocked: false,
    project1: null,
    project1Hours: 0,
    project1OT: 0,
    project2: null,
    project2Hours: 0,
    project2OT: 0,
    totalHours: 0,
    remarks: "",
    allowBreakProject1: true,
    allowBreakProject1Value: false,
    allowBreakProject2: true,
    allowBreakProject2Value: false,
  },
];

// Generate more rows to reach 24
for (let i = 7; i <= 24; i++) {
  initialTimesheetData.push({
    id: i,
    rowNumber: i,
    code: String(10000 + i * 1000),
    employeeName: `EMPLOYEE NAME ${i}`,
    designation: i % 3 === 0 ? "Mechanic" : i % 3 === 1 ? "Plumber" : "Laborer",
    hasFlag: i >= 7 && i <= 12,
    isLocked: false,
    project1: null,
    project1Hours: 0,
    project1OT: 0,
    project2: null,
    project2Hours: 0,
    project2OT: 0,
    totalHours: 0,
    remarks: "",
    allowBreakProject1: true,
    allowBreakProject1Value: false,
    allowBreakProject2: true,
    allowBreakProject2Value: false,
  });
}

export interface Project {
  id: number;
  nameEn: string;
  nameAr: string;
  isActive: boolean;
}

const projectsData: Project[] = [];

for (let i = 1; i <= 10; i++) {
  projectsData.push({
    id: i,
    nameEn: `Project ${i}`,
    nameAr: `المشروع ${i}`,
    isActive: i % 2 === 0,
  });
}

interface LoanEntry {
  id: number;
  date: string; // DD-Mon-YYYY format
  code: string; // 5-digit code
  employeeName: string;
  designation: string;
  amount: number;
  remarks: string;
  type: "loan" | "return";
}

const initialLoansData: LoanEntry[] = [
  {
    id: 1,
    date: "01-Dec-2025",
    code: "60045",
    employeeName: "TAIMOOR HASSAN MUHAMMAD WALAYAT",
    designation: "Truck House Driver",
    amount: 200,
    remarks: "Exit re-entry visa fess",
    type: "loan",
  },
  {
    id: 2,
    date: "04-Dec-2025",
    code: "90525",
    employeeName: "NADEEM ABBAS",
    designation: "OS, Carpenter",
    amount: 500,
    remarks: "Issue Iqama Process fee (Abu Mashal)",
    type: "return",
  },
  {
    id: 3,
    date: "08-Dec-2025",
    code: "10014",
    employeeName: "WAKIL AHMED CHOUDHURY",
    designation: "Data Operator",
    amount: 1000,
    remarks: "PV-6541",
    type: "loan",
  },
  {
    id: 4,
    date: "09-Dec-2025",
    code: "90668",
    employeeName: "WAQAR AHMED",
    designation: "Shavel Operator",
    amount: 200,
    remarks: "Advance taken by sajid aurangzeb",
    type: "return",
  },
  {
    id: 5,
    date: "10-Dec-2025",
    code: "90642",
    employeeName: "ZAKRIYA MUHAMMED",
    designation: "Carpenter",
    amount: 500,
    remarks: "Advance PV-6086",
    type: "loan",
  },
  {
    id: 6,
    date: "11-Dec-2025",
    code: "60062",
    employeeName: "SHAHADAT KHAN MUHAMMAD TUFAIL",
    designation: "Truck House Driver",
    amount: 2000,
    remarks: "Naqal Kafala fees",
    type: "return",
  },
  {
    id: 7,
    date: "12-Dec-2025",
    code: "40104",
    employeeName: "SHAD MUHAMMAD UMAR DAD",
    designation: "Carpenter",
    amount: 3000,
    remarks: "PV-6564 khafala Charges paid outside",
    type: "loan",
  },
  {
    id: 8,
    date: "13-Dec-2025",
    code: "40103",
    employeeName: "MUHAMMAD SAJID AURANGZEB",
    designation: "Data Operator",
    amount: 2500,
    remarks: "3 months iqama JAN, FEB, MAR 2026",
    type: "return",
  },
  {
    id: 9,
    date: "14-Dec-2025",
    code: "60065",
    employeeName: "ISHTIAQ AHMED MUHAMMAD SIDDIQUE",
    designation: "Truck House Driver",
    amount: 7500,
    remarks: "Jun 2025 to Feb 2026",
    type: "loan",
  },
  {
    id: 10,
    date: "15-Dec-2025",
    code: "60066",
    employeeName: "AHMED ALI KHAN",
    designation: "Shavel Operator",
    amount: 400,
    remarks: "Advance",
    type: "return",
  },
];

// Generate more entries to reach 152 total (as shown in pagination)
for (let i = 11; i <= 152; i++) {
  const designations = [
    "Truck House Driver",
    "OS, Carpenter",
    "Data Operator",
    "Shavel Operator",
    "Carpenter",
    "Site Supervisor",
    "Mechanical Engineer",
    "Electrician",
  ];
  const employeeNames = [
    "TAIMOOR HASSAN MUHAMMAD WALAYAT",
    "NADEEM ABBAS",
    "WAKIL AHMED CHOUDHURY",
    "WAQAR AHMED",
    "ZAKRIYA MUHAMMED",
    "SHAHADAT KHAN MUHAMMAD TUFAIL",
    "SHAD MUHAMMAD UMAR DAD",
    "MUHAMMAD SAJID AURANGZEB",
    "ISHTIAQ AHMED MUHAMMAD SIDDIQUE",
    "AHMED ALI KHAN",
    "MUHAMMAD HASSAN",
    "ALI AHMED",
    "HASSAN MUHAMMAD",
    "ABDUL RAHMAN",
    "OMAR ALI",
  ];
  const remarks = [
    "Exit re-entry visa fess",
    "Issue Iqama Process fee",
    "PV-6541",
    "Advance taken",
    "Advance PV-6086",
    "Naqal Kafala fees",
    "khafala Charges paid outside",
    "3 months iqama",
    "Advance",
    "Medical expenses",
    "Travel expenses",
    "Emergency loan",
  ];

  const day = String(Math.floor(Math.random() * 28) + 1).padStart(2, "0");
  const month = "Dec";
  const year = 2025;
  const code = String(Math.floor(Math.random() * 90000) + 10000);

  initialLoansData.push({
    id: i,
    date: `${day}-${month}-${year}`,
    code: code,
    employeeName:
      employeeNames[Math.floor(Math.random() * employeeNames.length)],
    designation: designations[Math.floor(Math.random() * designations.length)],
    amount: [200, 400, 500, 1000, 1500, 2000, 2500, 3000, 5000, 7500][
      Math.floor(Math.random() * 10)
    ],
    remarks: remarks[Math.floor(Math.random() * remarks.length)],
    type: i % 2 === 0 ? "loan" : "return",
  });
}

export {
  stats,
  projectsData,
  expensesByProject,
  branches,
  projects,
  months,
  employees,
  designationOptions,
  initialTimesheetData,
  initialLoansData,
};
export type { ProjectExpense, Employee, TimesheetEntry, LoanEntry };
